# Libreta en Jupyter usando R
### Estructuras de datos
Miércoles 26 de febrero 2025

In [4]:
#Crear un dato numérico.
a = 2025
a

[1] 2025

In [14]:
#funciones para verificar el tipo de dato
typeof(a)
class(a)

[1] "double"

[1] "numeric"

In [10]:
#Crear un dato categórico (string)
b = "Hola"
print(b)

[1] "Hola"


In [12]:
#Crear dato lógico
c = TRUE
c

[1] TRUE

In [13]:
#verificar tipo de datos
class(a)
class(b)
class(c)

[1] "numeric"

[1] "character"

[1] "logical"

## 1. Vectores

In [19]:
#vector numérico en R
v1<-c(1,2,3,4,5)
print(v1)
class(v1)
length(v1)

[1] 1 2 3 4 5


[1] "numeric"

[1] 5

In [20]:
#vector de caracteres en R
v2<-c("A","B","A","B","B")
print(v2)
class(v2)
length(v2)

[1] "A" "B" "A" "B" "B"


[1] "character"

[1] 5

In [23]:
#vector de valores lógicos (T / F)
v3<-c(TRUE, FALSE, TRUE, TRUE, FALSE)
print(v3)
class(v3)
length(v3)

[1]  TRUE FALSE  TRUE  TRUE FALSE


[1] "logical"

[1] 5

In [27]:
v4<-c(26,"clase",FALSE)
v4

[1] "26"    "clase" "FALSE"

In [30]:
typeof(v4)
class(v4)
is.vector(v4)

[1] "character"

[1] "character"

[1] TRUE

## 2. Matrices

In [31]:
?matrix

matrix                  package:base                   R Documentation

_M_a_t_r_i_c_e_s

_D_e_s_c_r_i_p_t_i_o_n:

     ‘matrix’ creates a matrix from the given set of values.

     ‘as.matrix’ attempts to turn its argument into a matrix.

     ‘is.matrix’ tests if its argument is a (strict) matrix.

_U_s_a_g_e:

     matrix(data = NA, nrow = 1, ncol = 1, byrow = FALSE,
            dimnames = NULL)
     
     as.matrix(x, ...)
     ## S3 method for class 'data.frame'
     as.matrix(x, rownames.force = NA, ...)
     
     is.matrix(x)
     
_A_r_g_u_m_e_n_t_s:

    data: an optional data vector (including a list or ‘expression’
          vector).  Non-atomic classed R objects are coerced by
          ‘as.vector’ and all attributes discarded.

    nrow: the desired number of rows.

    ncol: the desired number of columns.

   byrow: logical. If ‘FALSE’ (the default) the matrix is filled by
          columns, otherwise the matrix is filled by rows.

dimnames: A ‘dimnames’ attribute for the matrix: ‘NULL’ or a ‘list’ of
          length 2 giving the row and column names respectively.  An
          empty list is treated as ‘NULL’, and a list of length one as
          row names.  The list can be named, and the list names will be
          used as names for the dimensions.

       x: an R object.

     ...: additional arguments to be passed to or from methods.

rownames.force: logical indicating if the resulting matrix should have
          character (rather than ‘NULL’) ‘rownames’.  The default,
          ‘NA’, uses ‘NULL’ rownames if the data frame has ‘automatic’
          row.names or for a zero-row data frame.

_D_e_t_a_i_l_s:

     If one of ‘nrow’ or ‘ncol’ is not given, an attempt is made to
     infer it from the length of ‘data’ and the other parameter.  If
     neither is given, a one-column matrix is returned.

     If there are too few elements in ‘data’ to fill the matrix, then
     the elements in ‘data’ are recycled.  If ‘data’ has length zero,
     ‘NA’ of an appropriate type is used for atomic vectors (‘0’ for
     raw vectors) and ‘NULL’ for lists.

     ‘is.matrix’ returns ‘TRUE’ if ‘x’ is a vector and has a ‘"dim"’
     attribute of length 2 and ‘FALSE’ otherwise.  Note that a
     ‘data.frame’ is *not* a matrix by this test.  The function is
     generic: you can write methods to handle specific classes of
     objects, see InternalMethods.

     ‘as.matrix’ is a generic function.  The method for data frames
     will return a character matrix if there is only atomic columns and
     any non-(numeric/logical/complex) column, applying ‘as.vector’ to
     factors and ‘format’ to other non-character columns.  Otherwise,
     the usual coercion hierarchy (logical < integer < double <
     complex) will be used, e.g., all-logical data frames will be
     coerced to a logical matrix, mixed logical-integer will give a
     integer matrix, etc.

     The default method for ‘as.matrix’ calls ‘as.vector(x)’, and hence
     e.g. coerces factors to character vectors.

     When coercing a vector, it produces a one-column matrix, and
     promotes the names (if any) of the vector to the rownames of the
     matrix.

     ‘is.matrix’ is a primitive function.

     The ‘print’ method for a matrix gives a rectangular layout with
     dimnames or indices.  For a list matrix, the entries of length not
     one are printed in the form ‘integer,7’ indicating the type and
     length.

_N_o_t_e:

     If you just want to convert a vector to a matrix, something like

       dim(x) <- c(nx, ny)
       dimnames(x) <- list(row_names, col_names)
     
     will avoid duplicating ‘x’ _and_ preserve ‘class(x)’ which may be
     useful, e.g., for ‘Date’ objects.

_R_e_f_e_r_e_n_c_e_s:

     Becker, R. A., Chambers, J. M. and Wilks, A. R. (1988) _The New S
     Language_.  Wadsworth & Brooks/Cole.

_S_e_e _A_l_s_o:

     ‘data.matrix’, which attempts to convert to a numeric matrix

In [33]:
#matriz numérica
M1 = matrix(1:9,3,3)
M1

[,1] [,2] [,3]
[1,] 1    4    7   
[2,] 2    5    8   
[3,] 3    6    9

In [34]:
is.matrix(M1)

[1] TRUE

In [36]:
M2<-matrix(c(TRUE, FALSE, TRUE, FALSE, TRUE, FALSE),2,3)
M2

[,1]  [,2]  [,3] 
[1,]  TRUE  TRUE  TRUE
[2,] FALSE FALSE FALSE

In [41]:
M3<-matrix(c(3, FALSE, "Hola", -1, TRUE, "bye"),1,6)
M3

[,1] [,2]  [,3] [,4] [,5] [,6]
[1,] 3    FALSE Hola -1   TRUE bye

In [43]:
class(M3)
typeof(M3)

[1] "matrix" "array"

[1] "character"

In [46]:
ls() #Objetos guardados en la memoria

[1] "a"  "b"  "c"  "M1" "M2" "M3" "v1" "V1" "v2" "v3" "v4"

In [ ]:
remove(M4) #Eliminar objetos de la memoria

## 3. DataFrame

In [47]:
?data.frame

data.frame                package:base                 R Documentation

_D_a_t_a _F_r_a_m_e_s

_D_e_s_c_r_i_p_t_i_o_n:

     The function ‘data.frame()’ creates data frames, tightly coupled
     collections of variables which share many of the properties of
     matrices and of lists, used as the fundamental data structure by
     most of R's modeling software.

_U_s_a_g_e:

     data.frame(..., row.names = NULL, check.rows = FALSE,
                check.names = TRUE, fix.empty.names = TRUE,
                stringsAsFactors = FALSE)
     
_A_r_g_u_m_e_n_t_s:

     ...: these arguments are of either the form ‘value’ or ‘tag =
          value’.  Component names are created based on the tag (if
          present) or the deparsed argument itself.

row.names: ‘NULL’ or a single integer or character string specifying a
          column to be used as row names, or a character or integer
          vector giving the row names for the data frame.

check.rows: if ‘TRUE’ then the rows are checked for consistency of
          length and names.

check.names: logical.  If ‘TRUE’ then the names of the variables in the
          data frame are checked to ensure that they are syntactically
          valid variable names and are not duplicated.  If necessary
          they are adjusted (by ‘make.names’) so that they are.

fix.empty.names: logical indicating if arguments which are “unnamed”
          (in the sense of not being formally called as ‘someName =
          arg’) get an automatically constructed name or rather name
          ‘""’.  Needs to be set to ‘FALSE’ even when ‘check.names’ is
          false if ‘""’ names should be kept.

stringsAsFactors: logical: should character vectors be converted to
          factors?  The ‘factory-fresh’ default has been ‘TRUE’
          previously but has been changed to ‘FALSE’ for R 4.0.0.

_D_e_t_a_i_l_s:

     A data frame is a list of variables of the same number of rows
     with unique row names, given class ‘"data.frame"’.  If no
     variables are included, the row names determine the number of
     rows.

     The column names should be non-empty, and attempts to use empty
     names will have unsupported results.  Duplicate column names are
     allowed, but you need to use ‘check.names = FALSE’ for
     ‘data.frame’ to generate such a data frame.  However, not all
     operations on data frames will preserve duplicated column names:
     for example matrix-like subsetting will force column names in the
     result to be unique.

     ‘data.frame’ converts each of its arguments to a data frame by
     calling ‘as.data.frame(optional = TRUE)’.  As that is a generic
     function, methods can be written to change the behaviour of
     arguments according to their classes: R comes with many such
     methods.  Character variables passed to ‘data.frame’ are converted
     to factor columns if not protected by ‘I’ and argument
     ‘stringsAsFactors’ is true.  If a list or data frame or matrix is
     passed to ‘data.frame’ it is as if each component or column had
     been passed as a separate argument (except for matrices protected
     by ‘I’).

     Objects passed to ‘data.frame’ should have the same number of
     rows, but atomic vectors (see ‘is.vector’), factors and character
     vectors protected by ‘I’ will be recycled a whole number of times
     if necessary (including as elements of list arguments).

     If row names are not supplied in the call to ‘data.frame’, the row
     names are taken from the first component that has suitable names,
     for example a named vector or a matrix with rownames or a data
     frame.  (If that component is subsequently recycled, the names are
     discarded with a warning.)  If ‘row.names’ was supplied as ‘NULL’
     or no suitable component was found the row names are the integer
     sequence starting at one (and such row names are considered to be
     ‘automatic’, and not preserved by ‘as.matrix’).

   

In [50]:
#Crear los vectores
set.seed(123) #semilla para resultados reproducibles
x=round(runif(10, min=1, max=10),2) #crea secuencias de numeros aletatorios de una distribución uniforme.
x

[1] 3.59 8.09 4.68 8.95 9.46 1.41 5.75 9.03 5.96 5.11

In [51]:
?rep

rep                    package:base                    R Documentation

_R_e_p_l_i_c_a_t_e _E_l_e_m_e_n_t_s _o_f _V_e_c_t_o_r_s _a_n_d _L_i_s_t_s

_D_e_s_c_r_i_p_t_i_o_n:

     ‘rep’ replicates the values in ‘x’.  It is a generic function, and
     the (internal) default method is described here.

     ‘rep.int’ and ‘rep_len’ are faster simplified versions for two
     common cases.  Internally, they are generic, so methods can be
     defined for them (see InternalMethods).

_U_s_a_g_e:

     rep(x, ...)
     
     rep.int(x, times)
     
     rep_len(x, length.out)
     
_A_r_g_u_m_e_n_t_s:

       x: a vector (of any mode including a ‘list’) or a factor or (for
          ‘rep’ only) a ‘POSIXct’ or ‘POSIXlt’ or ‘Date’ object; or an
          S4 object containing such an object.

     ...: further arguments to be passed to or from other methods.  For
          the internal default method these can include:

          ‘times’ an integer-valued vector giving the (non-negative)
              number of times to repeat each element if of length
              ‘length(x)’, or to repeat the whole vector if of length
              1.  Negative or ‘NA’ values are an error.  A ‘double’
              vector is accepted, other inputs being coerced to an
              integer or double vector.

          ‘length.out’ non-negative integer.  The desired length of the
              output vector.  Other inputs will be coerced to a double
              vector and the first element taken.  Ignored if ‘NA’ or
              invalid.

          ‘each’ non-negative integer.  Each element of ‘x’ is repeated
              ‘each’ times.  Other inputs will be coerced to an integer
              or double vector and the first element taken.  Treated as
              ‘1’ if ‘NA’ or invalid.

times, length.out: see ‘...’ above.

_D_e_t_a_i_l_s:

     The default behaviour is as if the call was

       rep(x, times = 1, length.out = NA, each = 1)
     
     .  Normally just one of the additional arguments is specified, but
     if ‘each’ is specified with either of the other two, its
     replication is performed first, and then that implied by ‘times’
     or ‘length.out’.

     If ‘times’ consists of a single integer, the result consists of
     the whole input repeated this many times.  If ‘times’ is a vector
     of the same length as ‘x’ (after replication by ‘each’), the
     result consists of ‘x[1]’ repeated ‘times[1]’ times, ‘x[2]’
     repeated ‘times[2]’ times and so on.

     ‘length.out’ may be given in place of ‘times’, in which case ‘x’
     is repeated as many times as is necessary to create a vector of
     this length.  If both are given, ‘length.out’ takes priority and
     ‘times’ is ignored.

     Non-integer values of ‘times’ will be truncated towards zero.  If
     ‘times’ is a computed quantity it is prudent to add a small fuzz
     or use ‘round’.  And analogously for ‘each’.

     If ‘x’ has length zero and ‘length.out’ is supplied and is
     positive, the values are filled in using the extraction rules,
     that is by an ‘NA’ of the appropriate class for an atomic vector
     (‘0’ for raw vectors) and ‘NULL’ for a list.

_V_a_l_u_e:

     An object of the same type as ‘x’.

     ‘rep.int’ and ‘rep_len’ return no attributes (except the class if
     returning a factor).

     The default method of ‘rep’ gives the result names (which will
     almost always contain duplicates) if ‘x’ had names, but retains no
     other attributes.

_N_o_t_e:

     Function ‘rep.int’ is a simple case which was provided as a
     separate function partly for S compatibility and partly for speed
     (especially when names can be dropped).  The performance of ‘rep’
     has been improved since, but ‘rep.int’ is still at least twice as
     fast when ‘x’ has names.

     The name ‘rep.int’ long precedes making ‘rep’ generic.

     Function ‘rep’ is a primitive, but (partial) 

In [53]:
y=rep("hola",10)
y

[1] "hola" "hola" "hola" "hola" "hola" "hola" "hola" "hola" "hola" "hola"

In [55]:
z=rep(c(TRUE,FALSE), 5)
z

[1]  TRUE FALSE  TRUE FALSE  TRUE FALSE  TRUE FALSE  TRUE FALSE

In [56]:
#Tamaño de los vectores
length(x)
length(y)
length(z)

[1] 10

[1] 10

[1] 10

In [57]:
df=data.frame(X=x,Y=y,Z=z)
df

X    Y    Z    
1  3.59 hola  TRUE
2  8.09 hola FALSE
3  4.68 hola  TRUE
4  8.95 hola FALSE
5  9.46 hola  TRUE
6  1.41 hola FALSE
7  5.75 hola  TRUE
8  9.03 hola FALSE
9  5.96 hola  TRUE
10 5.11 hola FALSE

In [59]:
v1

[1] 1 2 3 4 5

In [60]:
#Caso no adecuado.
df2=data.frame(Var1=x,Var2=y,Var3=z, Var4=v1)
df2

Var1 Var2 Var3  Var4
1  3.59 hola  TRUE 1   
2  8.09 hola FALSE 2   
3  4.68 hola  TRUE 3   
4  8.95 hola FALSE 4   
5  9.46 hola  TRUE 5   
6  1.41 hola FALSE 1   
7  5.75 hola  TRUE 2   
8  9.03 hola FALSE 3   
9  5.96 hola  TRUE 4   
10 5.11 hola FALSE 5

## 4. Listas

In [61]:
?list

list                   package:base                    R Documentation

_L_i_s_t_s - _G_e_n_e_r_i_c _a_n_d _D_o_t_t_e_d _P_a_i_r_s

_D_e_s_c_r_i_p_t_i_o_n:

     Functions to construct, coerce and check for both kinds of R
     lists.

_U_s_a_g_e:

     list(...)
     pairlist(...)
     
     as.list(x, ...)
     ## S3 method for class 'environment'
     as.list(x, all.names = FALSE, sorted = FALSE, ...)
     as.pairlist(x)
     
     is.list(x)
     is.pairlist(x)
     
     alist(...)
     
_A_r_g_u_m_e_n_t_s:

     ...: objects, possibly named.

       x: object to be coerced or tested.

all.names: a logical indicating whether to copy all values or (default)
          only those whose names do not begin with a dot.

  sorted: a logical indicating whether the ‘names’ of the resulting
          list should be sorted (increasingly).  Note that this is
          somewhat costly, but may be useful for comparison of
          environments.

_D_e_t_a_i_l_s:

     Almost all lists in R internally are _Generic Vectors_, whereas
     traditional _dotted pair_ lists (as in LISP) remain available but
     rarely seen by users (except as ‘formals’ of functions).

     The arguments to ‘list’ or ‘pairlist’ are of the form ‘value’ or
     ‘tag = value’.  The functions return a list or dotted pair list
     composed of its arguments with each value either tagged or
     untagged, depending on how the argument was specified.

     ‘alist’ handles its arguments as if they described function
     arguments.  So the values are not evaluated, and tagged arguments
     with no value are allowed whereas ‘list’ simply ignores them.
     ‘alist’ is most often used in conjunction with ‘formals’.

     ‘as.list’ attempts to coerce its argument to a list.  For
     functions, this returns the concatenation of the list of formal
     arguments and the function body.  For expressions, the list of
     constituent elements is returned.  ‘as.list’ is generic, and as
     the default method calls ‘as.vector(mode = "list")’ for a
     non-list, methods for ‘as.vector’ may be invoked.  ‘as.list’ turns
     a factor into a list of one-element factors, keeping ‘names’.
     Other attributes may be dropped unless the argument already is a
     list or expression.  (This is inconsistent with functions such as
     ‘as.character’ which always drop attributes, and is for efficiency
     since lists can be expensive to copy.)

     ‘is.list’ returns ‘TRUE’ if and only if its argument is a ‘list’
     _or_ a ‘pairlist’ of ‘length’ > 0.  ‘is.pairlist’ returns ‘TRUE’
     if and only if the argument is a pairlist or ‘NULL’ (see below).

     The ‘"environment"’ method for ‘as.list’ copies the name-value
     pairs (for names not beginning with a dot) from an environment to
     a named list.  The user can request that all named objects are
     copied.  Unless ‘sorted = TRUE’, the list is in no particular
     order (the order depends on the order of creation of objects and
     whether the environment is hashed).  No enclosing environments are
     searched.  (Objects copied are duplicated so this can be an
     expensive operation.)  Note that there is an inverse operation,
     the ‘as.environment()’ method for list objects.

     An empty pairlist, ‘pairlist()’ is the same as ‘NULL’.  This is
     different from ‘list()’: some but not all operations will promote
     an empty pairlist to an empty list.

     ‘as.pairlist’ is implemented as ‘as.vector(x, "pairlist")’, and
     hence will dispatch methods for the generic function ‘as.vector’.
     Lists are copied element-by-element into a pairlist and the names
     of the list used as tags for the pairlist: the return value for
     other types of argument is undocumented.

     ‘list’, ‘is.list’ and ‘is.pairlist’ are primitive functions.

_R_e_f_e_r_e_n_c_e_s:

     Becker, R. A., Chambers, J. M. and Wilks, A. R. (1988) _The New S
     Language_.

In [62]:
#Crear una lista que guarde un dato, un vector, una matriz y un dataframe.

L1=list(a,v1,M1,df)
L1

[[1]]
[1] 2025

[[2]]
[1] 1 2 3 4 5

[[3]]
     [,1] [,2] [,3]
[1,]    1    4    7
[2,]    2    5    8
[3,]    3    6    9

[[4]]
      X    Y     Z
1  3.59 hola  TRUE
2  8.09 hola FALSE
3  4.68 hola  TRUE
4  8.95 hola FALSE
5  9.46 hola  TRUE
6  1.41 hola FALSE
7  5.75 hola  TRUE
8  9.03 hola FALSE
9  5.96 hola  TRUE
10 5.11 hola FALSE